version: "3.7"
services:
  angular:
    build: ../containers/angular
    volumes:
      - ../containers/angular/src:/var/local/angular/src
      - sitedata:/var/local/angular/dist/gpucomp-ang
    depends_on:
      - nginx
  python:
    build: ../containers/python
    environment: 
      PGUSER: ${PGUSER}
      PGHOST: ${PGHOST}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
    networks: 
      - postgres
  ebayapi:
    build: ../containers/ebayapi
    environment: 
      EBAY_API_KEY: ${EBAY_API_KEY}
      PGUSER: ${PGUSER}
      PGHOST: ${PGHOST}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
    networks: 
      - postgres
  api:
    build: ../containers/api
    volumes:
      - certs:/var/local/api/certs
      - ./.env:/var/local/api/.env
    depends_on:
      - selfsign
    ports:
      - "${API_PORT}:60777"
    entrypoint: npm run dev ${DOMAIN_NAME}
    environment: 
      PGUSER: ${PGUSER}
      PGHOST: ${PGHOST}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
    networks: 
      - postgres
  nginx:
    image: nginx:1.19.3-alpine
    volumes:
      - sitedata:/usr/share/nginx/html
      - certs:/home
      - ./nginx.conf:/etc/nginx/conf.d/gpu.conf
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    depends_on: 
      - api
      - selfsign
  selfsign:
    image: frapsoft/openssl #literally just a container with openssl installed, should define locally to be safe
    working_dir: /home
    entrypoint: openssl req -x509 -nodes -days 73000 -newkey rsa:2048 -subj "/CN=${DOMAIN_NAME}" -keyout privkey.pem -out fullchain.pem
    volumes:
      - certs:/home
  postgres:
    image: postgres:12
    container_name: ${PGHOST}
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
    networks: 
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    #db init moved to separate container
    #entrypoint: echo "create database ${PGDATABASE}; \c ${PGDATABASE}; create table gpulist(); create table gpudb(); create table lastupdate(); \dt;" >> init.sql && psql -U ${PGUSER} -f init.sql && tail -f /dev/null
  postgres-init:
    build: ../containers/postgres-init
    depends_on: 
      - postgres
    networks: 
      - postgres
    environment: 
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}

volumes:
  sitedata:
  certs:
  postgres:

networks: 
  postgres: