version: "3.7"
services:
  angular:
    build: ./angular
    volumes:
      - ./angular/src:/var/local/angular/src
      - sitedata:/var/local/angular/dist/gpucomp-ang
    depends_on:
      - nginx
  rust:
    build: ./rust
    volumes:
      - ./commonfiles:/var/local/commonfiles
  api:
    build: ./api
    volumes:
      - ./api/src:/var/local/api/src
      - ./commonfiles:/var/local/commonfiles
      - certs:/var/local/api/certs
    depends_on:
      - rust
      - certbot
    ports:
      - "60777:60777"
  nginx:
    image: nginx:1.19.3-alpine
    volumes:
      - sitedata:/usr/share/nginx/html
      - certs:/home
      - ./nginx-remote.comf:/erc/nginx/conf.d/gpu.conf
    ports:
      - "777:80"
      - "778:443"
    depends_on: 
      - api
      - certbot
  certbot:
    build:
      context: ./certbot
    args:
      DOMAIN_NAME: gpu.mhwdvs.com
      EMAIL_ADDRESS: public@mhwdvs.com
    volumes:
      - certs:/etc/letsencrypt/live/gpu.mhwdvs.com

volumes:
  sitedata:
  certs: