version: "3.7"
services:
  angular:
    build: ../containers/angular
    volumes:
      - ../containers/angular/src:/var/local/angular/src
      - sitedata:/var/local/angular/dist/gpucomp-ang
  python:
    container_name: python
    build: ../containers/python
    environment: 
      PGUSER: ${PGUSER}
      PGHOST: ${PGHOST}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
    networks: 
      - postgres
      - chromedriver
    depends_on: 
      - chromedriver
  chromedriver:
    container_name: chromedriver
    build: ../containers/chromedriver
    networks:
      - chromedriver
    environment: 
      CHROMEDRIVER_WHITELISTED_IPS: ''
  ebayapi:
    build: ../containers/ebayapi
    environment: 
      EBAY_API_KEY: ${EBAY_API_KEY}
      PGUSER: ${PGUSER}
      PGHOST: ${PGHOST}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
    networks: 
      - postgres
  api:
    build: ../containers/api
    volumes:
      - certs:/var/local/api/certs
      - ./.env:/var/local/api/.env
    depends-on:
      - postgres
    ports:
      - "${API_PORT}:60777"
    entrypoint: npm run dev ${DOMAIN_NAME}
    environment: 
      PGUSER: ${PGUSER}
      PGHOST: ${PGHOST}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
    networks: 
      - postgres
  postgres:
    image: postgres:12
    container_name: ${PGHOST}
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
    networks: 
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  postgres-init:
    build: ../containers/postgres-init
    depends_on: 
      - postgres
    networks: 
      - postgres
    environment: 
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
  apachesuperset:
    image: apache/superset
    depends-on:
      - postgres
    ports: 
      - 8088:8088
    entrypoint: ["/bin/sh", "-c", "superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin && superset db upgrade && superset load_examples && superset init && /usr/bin/docker-entrypoint.sh"]
    networks:
      - postgres
volumes:
  sitedata:
  postgres:
  certs:

networks: 
  postgres:
  chromedriver: