env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - google
parserOptions:
  ecmaVersion: 12
rules: {
  "max-len": "off",
  "no-multi-str": "off",
  "valid-jsdoc": "off",
  "require-jsdoc": "off"
}
parser: babel-eslint
